dry-dock/u16phpall

- install.sh
- version/5_4.sh
- version/5_5.sh
- version/5_6.sh
> Fix install scripts

- install.sh
> Fix php7.0-dev installation

- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
> Force phpunit 5.7

- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
closes https://github.com/dry-dock/u16phpall/issues/18
> run wget and curl with right flags

- install.sh
> Add librabbitmq

- version/5_6.sh
> Lock memcached-2.2.0 for PHP 5.6

- version/7_0.sh
- version/7_1.sh
> Remove memcache for PHP 7.x

- version/7_0.sh
- version/7_1.sh
> Remove mongo for PHP 7.x

- version/7_0.sh
- version/7_1.sh
> Add mongodb for PHP 7.x

- version/7_0.sh
- version/7_1.sh
> Use latest amqp for PHP 7.x

- install.sh
https://github.com/dry-dock/u16phpall/issues/35
> adds locale-gen

- Dockerfile
- README.md
- test/_php.sh
- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
fixes https://github.com/dry-dock/u16phpall/issues/37
verified the versions of  php on my local system
> update the latest versions of php in u16phpall

- install.sh
from https://github.com/dry-dock/u16phpall/issues/37
>  dont do any softlinks for tidy headers

- README.md
- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
https://github.com/dry-dock/u16phpall/issues/40
> update php versions for u16phpall

- README.md
- version/7_0.sh
- version/7_1.sh
closes https://github.com/dry-dock/u16phpall/issues/44
closes https://github.com/dry-dock/u16phpall/issues/45
> updgrades php

- install.sh
https://github.com/dry-dock/u16phpall/issues/53
>  updates env export

- README.md
- test/_php.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/10557
> PHP update version

- version/7_2.sh
https://github.com/Shippable/pm/issues/10557
> phpunit updated version

- test/_php.sh
https://github.com/Shippable/pm/issues/10557
> Test file update

- README.md
- version/7_1.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/11039
> instilling composer on php7.2 

- README.md
- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/11375
> latest updated version u16phpall image 

- install.sh
- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/11486
> updating php and phpunit 

- README.md
- version/5_6.sh
- version/7_0.sh
- version/7_1.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/11486
> updating  README.md file 

- README.md
- version/7_1.sh
- version/7_2.sh
https://github.com/Shippable/pm/issues/11549
> latest updated version for u16phpall image

- version/7_1.sh
- version/7_2.sh
- version/7_3.sh
https://github.com/Shippable/pm/issues/11676
> Enabling freetype extension for u16phpall images

- README.md
- version/7_1.sh
https://github.com/Shippable/pm/issues/11676
> Updating php version from 7.1.25 to 7.1.26 for u16phpall images 
